stages:
  evaluation:
    cmd: python src/model/evaluation.py
    deps:
    - src/model/evaluation.py
    - data/processed/train_trans.csv
    - data/processed/test_trans.csv
    - models/model.joblib
    outs:
    - run_information.json:
        cache: false

#   # register_model:
#   #   cmd: python src/models/register_model.py
#   #   deps:
#   #   - src/models/register_model.py
#   #   - run_information.json
